baseurl: /llm-course-notes
title: Probabilistic graphical modeling course
subtitle: LLMs course notes
author: thaihocnguyen
simple_search: http://google.com/search
description: Topic notes for LLMs
name: cs228-notes
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: Asia/Ho_Chi_Minh
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: main
transfer:
  command: rsync
  settings: -av
  source: _site/
